### ISSUE TITLE
Error bg.plot_file("demo.json")

### ISSUE THREAD

**Issue by SpamAllan** [evildmp/BrachioGraph#121]
Hey,

Beginner here. I've followed the tutorial through a couple of times but get an error when I run the bg.plot_file("demo.json"). Can anyone help?

>>> bg.plot_file("demo.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/BrachioGraph/plotter.py", line 176, in plot_file
    with open(filename, "r") as line_file:
FileNotFoundError: [Errno 2] No such file or directory: 'demo.json'

Thanks,
Sam

**Comment by andypiper** [comment]
late response so maybe you figured this out, but the docs specify `images/demo.json` for that file.
