### ISSUE TITLE
TypeError: autocontrast() got an unexpected keyword argument 'preserve_tone'

### ISSUE THREAD

**Issue by NonaSuomy** [evildmp/BrachioGraph#125]
Trying to use linedraw.py get this error. What modifications did you make to linedraw from the original git as I can't see this preserve_tone command in the original linedraw.py what would I need to do if I run the original from here https://github.com/LingDong-/linedraw to make it work with the brachiograph?

Thank you.

```bash
python
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from linedraw import *
>>> image_to_json("africa", draw_contours=2, draw_hatch=16)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/BrachioGraph/linedraw.py", line 40, in image_to_json
    lines = vectorise(
  File "/home/pi/BrachioGraph/linedraw.py", line 129, in vectorise
    image = ImageOps.autocontrast(image, 5, preserve_tone=True)
TypeError: autocontrast() got an unexpected keyword argument 'preserve_tone'
```

**Comment by NonaSuomy** [comment]
```bash
python3 -m pip install --upgrade pip
```
```bash
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (20.3.4)
Collecting pip
  Downloading https://www.piwheels.org/simple/pip/pip-23.1.2-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 330 kB/s
Installing collected packages: pip
  WARNING: The scripts pip, pip3 and pip3.9 are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.1.2
```
```bash
python3 -m pip install --upgrade Pillow
```
```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (8.1.2)
Collecting Pillow
  Downloading Pillow-9.5.0-cp39-cp39-manylinux_2_28_aarch64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 4.0 MB/s eta 0:00:00
Installing collected packages: Pillow
Successfully installed Pillow-9.5.0
```
```python
python
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Image.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Image' is not defined
>>> PIL.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PIL' is not defined
>>> from linedraw import *
>>> image_to_json("africa", draw_contours=2, draw_hatch=16)
Generating contours...
Finding edges...
Getting contour points...
Connecting contour points...
Getting contour points...
Connecting contour points...
Optimising line sequence...
Reduced 34 lines to 31 lines.
Optimising line sequence...
Reduced 437 lines to 189 lines.
220 lines, 997 segments.
Generating svg file...
```
Now it's working.
