### ISSUE TITLE
AttributeError: 'str' object has no attribute 'wait'

### ISSUE THREAD

**Issue by psytel** [evildmp/BrachioGraph#73]
Hey there!

I am new to python and raspberry so I managed to install everything and now trying to test a svg image. I get this output:

>>> BrachioGraph.plot_file("africa.svg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/psytel/BrachioGraphVM/BrachioGraph/brachiograph.py", line 136, in plot_file
    wait = wait or self.wait
AttributeError: 'str' object has no attribute 'wait'

Could someone help me? Thanks a lot :)
cheers

**Comment by meli94** [comment]
Hey, I have the same issue. Did you manage to fix it?

**Comment by Anustart1** [comment]
I have the same problem, I wish someone could help

**Comment by scholzco** [comment]
Are there any updates regarding this issue?

**Comment by john104433** [comment]
That's right I think.  You have to plot the africa.json file.
