### ISSUE TITLE
Trying to plot my first file: Exception: 'str' object has no attribute 'wait'

### ISSUE THREAD

**Issue by Trampf** [evildmp/BrachioGraph#76]
Hello, 

as mentioned above, when I try to plot my first json file (africa.json) from the tutorial I get the following exception:

`
>>> bg = BrachioGraph(inner_arm=8, outer_arm=8, bounds=[-5, 4, 5, 15], servo_1_centre=1460, servo_2_centre=1470)
>>> BrachioGraph.plot_file("africa.json")                                       Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/BrachioGraph/brachiograph.py", line 155, in plot_file
    wait = wait or self.wait
AttributeError: 'str' object has no attribute 'wait'

`

**Comment by Trampf** [comment]
Got it!

You have to use bg. instead of BrachioGraph and use the whole filepath.

Got it running with:

` bg.plot_file("/home/pi/BrachioGraph/images/africa.json")`
