### ISSUE TITLE
Issue with the base example. `Cannot reach ...`

### ISSUE THREAD

**Issue by jcrodriguez1989** [evildmp/BrachioGraph#93]
Hi, thanks for this great project!
I am having an issue with the base example at https://www.brachiograph.art/ .
I have my plotter set with 3 sg90 servos, with both arms of 8cm, really similar to the default pictures, however, when running the `africa` example I am getting an error:

```python
>>> # transform image to json format
>>> from linedraw import *
>>> image_to_json("africa", draw_contours=2, draw_hatch=16)
>>> 
>>> # start drawing
>>> from brachiograph import BrachioGraph
>>> inner_arm=8
>>> outer_arm=8
>>> bounds=[2, 2, 12, 12]
>>> bg = BrachioGraph(inner_arm=8, outer_arm=8, bounds=bounds)
>>> bg.plot_file('images/africa.json')
Traceback (most recent call last):                                                                                                                
  File "<stdin>", line 3, in <module>                                                                                                             
  File "/home/pi/Projects/BrachioGraph/brachiograph.py", line 164, in plot_file
    self.plot_lines(lines=lines, wait=wait, interpolate=interpolate, bounds=bounds, flip=True)
  File "/home/pi/Projects/BrachioGraph/brachiograph.py", line 182, in plot_lines
    self.xy(x, y, wait=wait, interpolate=interpolate)
  File "/home/pi/Projects/BrachioGraph/brachiograph.py", line 439, in xy
    (angle_1, angle_2) = self.xy_to_angles(x, y)
  File "/home/pi/Projects/BrachioGraph/brachiograph.py", line 608, in xy_to_angles
    raise Exception(f"Cannot reach {hypotenuse}; total arm length is {self.INNER_ARM + self.OUTER_ARM}")
Exception: Cannot reach 16.53000294101356; total arm length is 16
```

If `bounds` are specified, why is it trying to get out of it? How can I avoid this? Maybe limiting the image bounds?

Thank you very much!
Dr. Juan C Rodriguez

**Comment by jcrodriguez1989** [comment]
Ok, so this `bounds` was working with `bg.box()`. However, when using `plot_file`, `flip` is `True` so the bounds did not work in this case, I had just to recalculate bounds.
I think it is not clear how this `bounds` should be measured.
Thanks!
